version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - HOST=0.0.0.0
      - PORT=5001
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend:/app
    networks:
      - bhabit-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - bhabit-network

networks:
  bhabit-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
