services:
  - type: web
    name: bhabit-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /api/server-info
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: API_RATE_LIMIT
        value: "1000"
      - key: CACHE_TTL
        value: "60"
