#!/bin/bash

# BHABIT CBMOONERS - Application Startup Script
# This script starts both the backend Flask server and frontend Vite development server

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
  echo -e "${BLUE}[BHABIT]${NC} $1"
}

print_success() {
  echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_error() {
  echo -e "${RED}[ERROR]${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}[WARNING]${NC} $1"
}

# Function to check if a command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Function to cleanup background processes on exit
cleanup() {
  print_status "Shutting down servers..."
  if [ ! -z "$BACKEND_PID" ]; then
    kill $BACKEND_PID 2>/dev/null || true
  fi
  if [ ! -z "$FRONTEND_PID" ]; then
    kill $FRONTEND_PID 2>/dev/null || true
  fi
  print_success "Servers stopped."
}

# Set up cleanup trap
trap cleanup EXIT INT TERM

print_status "Starting BHABIT CBMOONERS Application..."

# Load .env if present (for OPENAI_API_KEY etc.)
if [ -f .env ]; then
  print_status "Loading environment from .env"
  # shellcheck disable=SC2046
  export $(grep -v '^#' .env | xargs -I{} echo {}) 2>/dev/null || true
fi

# Check required commands
if ! command_exists python3; then
  print_error "Python 3 is not installed. Please install Python 3.13+ to continue."
  exit 1
fi

if ! command_exists npm; then
  print_error "Node.js/npm is not installed. Please install Node.js 22.17+ to continue."
  exit 1
fi

# Check if backend exists
if [ ! -f "backend/app.py" ]; then
  print_error "Backend server not found! Please ensure 'backend/app.py' exists."
  exit 1
fi

# Check if frontend exists
if [ ! -d "frontend" ]; then
  print_error "Frontend directory not found! Please ensure 'frontend/' directory exists."
  exit 1
fi

# Activate virtual environment if it exists
if [ -d ".venv" ]; then
  print_status "Activating Python virtual environment..."
  source .venv/bin/activate
  print_success "Virtual environment activated."
else
  print_warning "No virtual environment found. Consider creating one with: python3 -m venv .venv"
fi

# Install backend dependencies if needed
if [ -f "backend/requirements.txt" ]; then
  print_status "Checking backend dependencies..."
  cd backend
  # Allow PyO3-based wheels (pydantic-core) to build against stable ABI on newer Python
  export PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  pip install -q -r requirements.txt
  cd ..
  print_success "Backend dependencies verified."
fi

# Install frontend dependencies if needed
print_status "Checking frontend dependencies..."
cd frontend
if [ ! -d "node_modules" ]; then
  print_status "Installing frontend dependencies..."
  npm install
fi
cd ..

print_success "Frontend dependencies verified."

# Ensure frontend knows where the backend API is (Vite env)
if [ -d "frontend" ]; then
  print_status "Writing frontend/.env.local with API base..."
  cat > frontend/.env.local <<'EOF'
# Auto-generated by start_app.sh
# Frontend will call the backend through this base URL
VITE_API_BASE=http://localhost:5001
# Optional: if your frontend uses a relative /api path with Vite proxy, set this to 1
VITE_USE_PROXY=0
EOF
  print_success "Wrote frontend/.env.local (VITE_API_BASE=http://localhost:5001)."
fi

# Ensure target ports are free before (re)starting
free_port() {
  local PORT=$1
  if command -v lsof >/dev/null 2>&1; then
    local PIDS
    PIDS=$(lsof -ti tcp:$PORT 2>/dev/null || true)
    if [ -n "$PIDS" ]; then
      print_warning "Port $PORT is in use by PID(s): $PIDS — sending TERM"
      kill $PIDS 2>/dev/null || true
      # give processes a moment to exit gracefully
      sleep 1
      # if still running, force kill
      local STILL
      STILL=$(lsof -ti tcp:$PORT 2>/dev/null || true)
      if [ -n "$STILL" ]; then
        print_warning "PID(s) still on $PORT after TERM; sending KILL"
        kill -9 $STILL 2>/dev/null || true
      fi
    fi
  elif command -v fuser >/dev/null 2>&1; then
    print_warning "Freeing port $PORT using fuser"
    fuser -k -n tcp $PORT 2>/dev/null || true
  else
    print_warning "Neither lsof nor fuser available; cannot auto-free port $PORT"
  fi
}

# Common dev ports: backend(5001), alt(5000), vite(5173). Also handle 5713 typo.
for PORT in 5000 5001 5173 5713; do
  free_port $PORT
done

# Start backend server
print_status "Preparing log files..."
# Truncate previous logs so tail shows fresh output
: > backend.log
: > frontend.log

print_status "Starting backend server on http://localhost:5001 (logs -> backend.log)..."
cd backend
# Use a fixed port for the backend so the frontend can reliably reach it.
# We proactively free the port earlier, then pass --kill-port and --port
# so the server binds to 5001 instead of auto‑selecting a random port
# (which previously caused the frontend to point at the wrong API base).
python3 app.py --kill-port --port 5001 > ../backend.log 2>&1 &
BACKEND_PID=$!
cd ..

# Wait a moment for backend to start
sleep 3

if ! ps -p $BACKEND_PID > /dev/null; then
  print_error "Backend server failed to start! See backend.log for details."
  tail -n +1 backend.log || true
  exit 1
fi
print_success "Backend server started successfully (PID: $BACKEND_PID)"

print_status "Starting frontend development server (logs -> frontend.log)..."
cd frontend
# Export Vite envs for this shell session too
set -a
[ -f .env.local ] && source .env.local || true
set +a
# run npm in non-interactive mode and capture output
npm run dev > ../frontend.log 2>&1 &
FRONTEND_PID=$!
cd ..

# Wait a moment for frontend to start
sleep 3

if ! ps -p $FRONTEND_PID > /dev/null; then
  print_error "Frontend server failed to start! See frontend.log for details."
  tail -n +1 frontend.log || true
  exit 1
fi
print_success "Frontend server started successfully (PID: $FRONTEND_PID)"

print_success "🐰 BHABIT CBMOONERS is now running!"
print_status "Backend API: http://localhost:5001"
print_status "Frontend App: http://localhost:5173"
print_status "Press Ctrl+C to stop both servers"

print_status "Streaming backend and frontend logs (press Ctrl+C to stop):"

# Stream both logs in the foreground so the user sees live output.
# When the user presses Ctrl+C this tail will exit and the trap will run cleanup().
tail -f backend.log frontend.log

# If tail exits for any reason, wait for background processes to exit as well
wait
